# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'fintec-demo-api:development-$(build.buildId)'
  dockerId: 
  dockerPwd:

steps:
- script: docker build -f Dockerfile --build-args CONFIGURATION=Debug -t $(imageName) .
  displayName: 'docker build: fintec-demo-api'
- script: |
        docker login -u $(dockerId) -p $(dockerPwd)
        docker push $(dockerId)/$(imageName)
